### ISSUE TITLE
The require package is wrong

### ISSUE THREAD

**Issue by KonghaYao** [yisibl/node-woff2-rs#1]
The import location of this project is wrong. It should import @woff2/woff2-rs-win32-x64-msvc and all the paths are incorrect. 😂

![image](https://github.com/yisibl/node-woff2-rs/assets/68177907/9db90351-63e9-47b4-b0dc-df56413b3820)
✅This means it has run successfully. 😄
![image](https://github.com/yisibl/node-woff2-rs/assets/68177907/91bc4eb8-772d-4939-ad2f-bd9fce02af24)

**Comment by yisibl** [comment]
😂 Thanks for the feedback, a new npm version has been released.
