### ISSUE TITLE
feat: 自动识别平台依赖并安装

### ISSUE THREAD

**Issue by KonghaYao** [yisibl/node-woff2-rs#3]
我使用您的仓库去构建了一个在 node 端生成字体预览的库。发现使用者需要自行安装平台相关的依赖。我就使用 postinstall 加 下面这个脚本实现了自动加载对应的平台适配依赖，这样我的项目就不用让用户自己安装了。😄

https://github.com/KonghaYao/cn-font-split/blob/29094edd919cedc705f05b92338d07180baeb6ff/packages/image-text/scripts/install.mjs#L5-L28

**Comment by yisibl** [comment]
啥意思，没看懂。

这个项目使用  [optionalDependencies](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies) 来自动识别不同的平台，只需要在你的项目中添加 `@woff2/woff2-rs` 就可以了，其他的会自动根据平台下载。可以看看这个文章：https://zhuanlan.zhihu.com/p/234914336

最终发布的 npm package.json 中会包含 optionalDependencies ：https://www.npmjs.com/package/@woff2/woff2-rs?activeTab=code

```json
"optionalDependencies": {
    "@woff2/woff2-rs-win32-x64-msvc": "1.0.1",
    "@woff2/woff2-rs-darwin-x64": "1.0.1",
    "@woff2/woff2-rs-linux-x64-gnu": "1.0.1",
    "@woff2/woff2-rs-linux-x64-musl": "1.0.1",
    "@woff2/woff2-rs-linux-arm64-gnu": "1.0.1",
    "@woff2/woff2-rs-win32-ia32-msvc": "1.0.1",
    "@woff2/woff2-rs-linux-arm-gnueabihf": "1.0.1",
    "@woff2/woff2-rs-darwin-arm64": "1.0.1",
    "@woff2/woff2-rs-android-arm64": "1.0.1",
    "@woff2/woff2-rs-freebsd-x64": "1.0.1",
    "@woff2/woff2-rs-linux-arm64-musl": "1.0.1",
    "@woff2/woff2-rs-win32-arm64-msvc": "1.0.1",
    "@woff2/woff2-rs-android-arm-eabi": "1.0.1"
  }
```

**Comment by KonghaYao** [comment]
抱歉，npm 确实会自动安装依赖，是我搞错了😂
